# The Sky page: a one-page showcase of the weewx-skyfield almanac.
# Copyright (C)2022-2026 by John A Kline (john@johnkline.com)
# Distributed under the terms of the GNU Public License (GPLv3)

SKIN_NAME = Skyfield
SKIN_VERSION = 1.9

[CheetahGenerator]
    encoding = html_entities
    search_list_extensions = user.wxskyfield_sky.SkyfieldSky
    [[ToDate]]
        [[[index]]]
            template = index.html.tmpl

[CopyGenerator]
    # The stylesheet only needs to be copied once.
    copy_once = sky.css

[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
